# Generated by Django 5.2.15 on 2026-07-07 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0006_organization_keycloak_group_path_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("periodo_retencion_meses", models.PositiveIntegerField()),
                ("worm_habilitado", models.BooleanField(default=True)),
                ("es_sensible", models.BooleanField(default=False)),
                (
                    "aprobadores_disposicion_requeridos",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_classes",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "nombre", "id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_types",
                        to="identity.organization",
                    ),
                ),
                (
                    "retention_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_types",
                        to="retention_disposition.retentionclass",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "nombre", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="retentionclass",
            constraint=models.UniqueConstraint(
                fields=("organization", "nombre"),
                name="uniq_retention_class_org_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("aprobadores_disposicion_requeridos__gte", 1)),
                name="retention_class_aprobadores_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttype",
            constraint=models.UniqueConstraint(
                fields=("organization", "nombre"), name="uniq_document_type_org_nombre"
            ),
        ),
    ]
