# Generated by Django 5.2.15 on 2026-07-03 21:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_system_roles(apps, schema_editor):
    Role = apps.get_model("identity", "Role")
    roles = {
        "P1": (
            "Auditor Líder",
            [
                "manage_findings",
                "decide_closure_branch",
                "verify_capa_effectiveness",
                "read",
            ],
        ),
        "P2": ("Auditor", ["manage_findings", "read"]),
        "P3": ("Auditado", ["appeal_finding_fact", "create_capa", "read"]),
        "P4": ("Gestor Documental", ["request_disposition", "read"]),
        "P5": (
            "Responsable de Programa",
            [
                "commission_audit",
                "verify_capa_effectiveness",
                "approve_disposition",
                "read",
            ],
        ),
        "P6": ("Administrador del Tenant", ["manage_memberships", "read"]),
        "P7": ("Auditor Externo", ["read"]),
    }
    for code, (name, capabilities) in roles.items():
        Role.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "capabilities": sorted(capabilities),
                "is_system": True,
            },
        )


def unseed_system_roles(apps, schema_editor):
    Role = apps.get_model("identity", "Role")
    Role.objects.filter(code__in=["P1", "P2", "P3", "P4", "P5", "P6", "P7"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "identity",
            "0002_organization_user_display_name_user_email_verified_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("P1", "Auditor Líder"),
                            ("P2", "Auditor"),
                            ("P3", "Auditado"),
                            ("P4", "Gestor Documental"),
                            ("P5", "Responsable de Programa"),
                            ("P6", "Administrador del Tenant"),
                            ("P7", "Auditor Externo"),
                        ],
                        help_text="Stable P1-P7 system role code.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Read-only system capability slugs enforced server-side."
                        ),
                    ),
                ),
                ("is_system", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MembershipRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="identity.membership",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_assignments",
                        to="identity.role",
                    ),
                ),
            ],
            options={
                "ordering": ["membership_id", "role__code"],
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="memberships",
                through="identity.MembershipRole",
                to="identity.role",
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiprole",
            constraint=models.UniqueConstraint(
                fields=("membership", "role"), name="uniq_membership_role"
            ),
        ),
        migrations.RunPython(seed_system_roles, unseed_system_roles),
    ]
