# Generated by Django 5.2.15 on 2026-07-06 18:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_rbac_roles_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakReplicationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        help_text="Keycloak event id; the replication dedupe key.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("event_type", models.CharField(blank=True, max_length=120)),
                ("operation", models.CharField(blank=True, max_length=32)),
                ("keycloak_sub", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
