# Generated by Django 5.2.15 on 2026-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_keycloakreplicationevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="origin",
            field=models.CharField(
                choices=[("keycloak", "Keycloak"), ("manual", "Manual")],
                default="manual",
                help_text=(
                    "Who owns this row's lifecycle. Keycloak group replication "
                    "only creates/prunes `keycloak` rows and never touches "
                    "`manual` ones."
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="keycloak_group_id",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Keycloak group id this org mirrors. NULL for "
                    "locally-managed orgs; the strong join key for "
                    "group-membership replication."
                ),
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="keycloak_group_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text=(
                    "Keycloak full group path (e.g. /parent/child). The token "
                    "`groups` claim carries paths, not ids, so login "
                    "reconciliation matches on it."
                ),
                max_length=512,
            ),
        ),
    ]
