# Generated by Codex for AUR-6.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "key",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
