# Generated by Django 5.2.15 on 2026-07-07 22:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_version", models.PositiveIntegerField()),
                ("hash_contenido", models.CharField(editable=False, max_length=64)),
                ("uri_almacenamiento", models.CharField(max_length=1024)),
                ("es_firmada", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["document_id", "numero_version", "id"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "estado_ciclo_vida",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_revision", "En revisión"),
                            ("publicado", "Publicado"),
                            ("retenido", "Retenido"),
                            ("dispuesto", "Dispuesto"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "titulo", "id"],
            },
        ),
    ]
