# Generated by Django 5.2.15 on 2026-07-07 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("identity", "0006_organization_keycloak_group_path_unique"),
        ("retention_disposition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="retention_disposition.documenttype",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="identity.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_document_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="documents.document",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "estado_ciclo_vida"],
                name="document_org_estado_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "document_type"], name="document_org_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["hash_contenido"], name="document_version_hash_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "numero_version"),
                name="uniq_document_version_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "hash_contenido"), name="uniq_document_version_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero_version__gte", 1)),
                name="document_version_number_gte_1",
            ),
        ),
    ]
