# Generated by Django 5.2.15 on 2026-07-03 17:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "identity",
            "0002_organization_user_display_name_user_email_verified_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="FindingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_snapshot",
                    models.EmailField(
                        help_text="Historical assignee email snapshot (ADR-0002).",
                        max_length=254,
                    ),
                ),
                (
                    "display_name_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Assignee display name snapshot (ADR-0002).",
                        max_length=255,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finding_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="findings_capa.finding",
                    ),
                ),
            ],
            options={
                "ordering": ["finding_id", "assigned_at", "id"],
            },
        ),
    ]
