# Generated by Django 5.2.15 on 2026-07-03 17:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "identity",
            "0002_organization_user_display_name_user_email_verified_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_email_snapshot",
                    models.EmailField(
                        help_text="Historical actor email snapshot (ADR-0002).",
                        max_length=254,
                    ),
                ),
                (
                    "actor_display_name_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Historical actor display name snapshot (ADR-0002).",
                        max_length=255,
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("target_entity", models.CharField(max_length=120)),
                ("target_id", models.UUIDField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("sequence", models.PositiveBigIntegerField()),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                ("entry_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trail_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trail_entries",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "sequence"),
                        name="uniq_trail_entry_organization_sequence",
                    )
                ],
            },
        ),
    ]
