# Generated by Django 5.2.15 on 2026-07-07 18:55

import django.db.models.deletion
from django.db import migrations, models


def backfill_ledger_head(apps, schema_editor):
    """Seed one LEDGER_HEAD per org, preserving existing trail tips.

    ADR-0008 needs a stable lock row before append paths run. Organizations
    with entries are seeded from their current tip; empty organizations get genesis.
    """

    TrailEntry = apps.get_model("trail", "TrailEntry")
    LedgerHead = apps.get_model("trail", "LedgerHead")

    Organization = apps.get_model("identity", "Organization")

    for organization_id in Organization.objects.values_list("id", flat=True):
        tip = (
            TrailEntry.objects.filter(organization_id=organization_id)
            .order_by("-sequence")
            .first()
        )
        LedgerHead.objects.update_or_create(
            organization_id=organization_id,
            defaults={
                "ultima_secuencia": tip.sequence if tip else 0,
                "ultimo_hash": tip.entry_hash if tip else "",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_organization_keycloak_group_path_unique"),
        ("trail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerHead",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="ledger_head",
                        serialize=False,
                        to="identity.organization",
                    ),
                ),
                ("ultima_secuencia", models.PositiveBigIntegerField(default=0)),
                ("ultimo_hash", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            backfill_ledger_head,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
