# Generated by Django 5.2.15 on 2026-07-07 18:55

import django.db.models.deletion
from django.db import migrations, models


def backfill_ledger_head(apps, schema_editor):
    """Seed one LEDGER_HEAD per org that already has trail entries, from its current tip.

    Orgs with no entries need no row; ``append_trail_entry`` seeds them lazily on first
    append. This keeps pre-existing chains continuous instead of restarting the tip at 0.
    """

    TrailEntry = apps.get_model("trail", "TrailEntry")
    LedgerHead = apps.get_model("trail", "LedgerHead")

    organization_ids = (
        TrailEntry.objects.order_by()
        .values_list("organization_id", flat=True)
        .distinct()
    )
    for organization_id in organization_ids:
        tip = (
            TrailEntry.objects.filter(organization_id=organization_id)
            .order_by("-sequence")
            .first()
        )
        LedgerHead.objects.update_or_create(
            organization_id=organization_id,
            defaults={
                "ultima_secuencia": tip.sequence,
                "ultimo_hash": tip.entry_hash,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_organization_keycloak_group_path_unique"),
        ("trail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerHead",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="ledger_head",
                        serialize=False,
                        to="identity.organization",
                    ),
                ),
                ("ultima_secuencia", models.PositiveBigIntegerField(default=0)),
                ("ultimo_hash", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            backfill_ledger_head,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
