# Generated by Django 5.2.15 on 2026-07-07 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0006_organization_keycloak_group_path_unique"),
        ("trail", "0002_ledgerhead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trailentry",
            options={},
        ),
        migrations.AddIndex(
            model_name="trailentry",
            index=models.Index(
                fields=["organization", "target_entity", "target_id", "sequence"],
                name="trail_entry_org_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trailentry",
            index=models.Index(
                fields=["organization", "actor", "sequence"],
                name="trail_entry_org_actor_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trailentry",
            index=models.Index(
                fields=["organization", "created_at"],
                name="trail_entry_org_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trailentry",
            index=models.Index(
                fields=["organization", "action", "sequence"],
                name="trail_entry_org_action_idx",
            ),
        ),
    ]
