# Generated by Django 5.2.15 on 2026-07-07 22:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0006_organization_keycloak_group_path_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INTERNA", "Interna"),
                            ("SEGUNDA_PARTE", "Segunda parte"),
                            ("TERCERA_PARTE", "Tercera parte"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICADA", "Planificada"),
                            ("EN_EJECUCION", "En ejecución"),
                            ("EN_CIERRE", "En cierre"),
                            ("INFORME_EMITIDO", "Informe emitido"),
                            ("EN_SEGUIMIENTO", "En seguimiento"),
                            ("CERRADA", "Cerrada"),
                            ("CANCELADA", "Cancelada"),
                            ("POSTERGADA", "Postergada"),
                        ],
                        default="PLANIFICADA",
                        max_length=20,
                    ),
                ),
                (
                    "estado_pre_postergacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLANIFICADA", "Planificada"),
                            ("EN_EJECUCION", "En ejecución"),
                            ("EN_CIERRE", "En cierre"),
                            ("INFORME_EMITIDO", "Informe emitido"),
                            ("EN_SEGUIMIENTO", "En seguimiento"),
                            ("CERRADA", "Cerrada"),
                            ("CANCELADA", "Cancelada"),
                            ("POSTERGADA", "Postergada"),
                        ],
                        help_text=(
                            "Estado origen para reanudar auditorías postergadas."
                        ),
                        max_length=20,
                    ),
                ),
                ("motivo_excepcion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_processes",
                        to="identity.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "estado"],
                        name="audit_proce_organiz_57fa70_idx",
                    ),
                    models.Index(
                        fields=["organization", "tipo"],
                        name="audit_proce_organiz_4a7362_idx",
                    ),
                ],
            },
        ),
    ]
